apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: my-dep
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP

