apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: test
  name: test
spec:
  replicas: 10
  selector:
    matchLabels:
      environment: test
  template:
    metadata:
      labels:
        environment: test
    spec:
      containers:
      - image: nginx:1.16
        name: nginx
        resources:
          requests:
            cpu: "1"      # 100 milliCPU (0.1 CPU)
            memory: "1024Mi"  # 256 Mebibytes
          limits:
            cpu: "1"      # 200 milliCPU (0.2 CPU)
            memory: "1024Mi"  # 512 Mebibytes
