# creates service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dqjenkins-sa
  namespace: dqjenkins-ns
  labels:
    name: dqjenkins-sa
    project: dq
    env: prod

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dqjenkins-role
  namespace: dqjenkins-ns
  labels:
    name: dqjenkins-role
    project: dq
    env: prod
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dqjenkins-rolebinding
  namespace: dqjenkins-ns
  labels:
    name: dqjenkins-rolebinding
    project: dq
    env: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dqjenkins-role
subjects:
  - kind: ServiceAccount
    name: dqjenkins-sa
    namespace: dqjenkins-ns
