apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-env
  name: pod-env
spec:
  containers:
  - command: [ 'sleep','1000']
    image: busybox
    name: pod-env
    env:
      - name: CONFIG
        valueFrom:
          configMapKeyRef:
            name: my-configmap
            key: key1
      - name: SECRET
        valueFrom:
          secretKeyRef:
            name: my-generic-secret
            key: secret1
